ARG VERSION=latest
FROM dockbuild/almalinux8-devtoolset14-gcc14:${VERSION}

LABEL maintainer="3D Slicer Community <slicer-devel@bwh.harvard.edu>"

ARG QT_ACCOUNT_LOGIN
ARG QT_ACCOUNT_PASSWORD

#include "common.pre-exec"

RUN \
  #
  # Qt dependencies:
  #
  # * https://doc.qt.io/qt-6/linux-requirements.html
  # * https://doc.qt.io/qt-6/supported-platforms.html
  #
dnf install -y\
    epel-release \
&& \
dnf install -y\
    fontconfig-devel \
    freetype-devel \
    gtk3-devel \
    libX11-devel \
    libX11-xcb \
    libxcb-devel \
    xcb-util-cursor-devel \
    xcb-util-renderutil-devel \
    xcb-util-image-devel \
    xcb-util-keysyms-devel \
    xcb-util-wm-devel \
    xcb-util-devel \
    libxcb-devel \
    libXrender-devel \
    libXext-devel \
    libXfixes-devel \
    libXi-devel \
    libxkbcommon-devel \
    libxkbcommon-x11-devel \
    xorg-x11-proto-devel \
    at-spi2-core-devel \
    mesa-libGL-devel \
    mesa-libEGL-devel \
  && \
  # Dependencies of Xvfb GLX environment
  dnf install -y \
    xorg-x11-server-Xvfb \
    xorg-x11-server-Xorg \
    mesa-dri-drivers \
    glx-utils \
  && \
  dnf install -y \
    alsa-lib \
    libXcomposite \
    libXcursor \
    libXrandr \
    libXtst \
    nss \
    mesa-libEGL \
  && \
  dnf install -y \
    pulseaudio-libs \
    pulseaudio-libs-glib2 \
  && \
  #
  # Slicer dependencies
  #
  dnf install -y \
    subversion \
  && \
  #
  # SlicerJupyter dependencies
  #
  dnf install -y \
    libuuid-devel \
  && \
  #
  # SlicerIMSTK dependencies
  #
  dnf install -y \
    libusbx-devel \
  && \
  #
  # Download and install Qt: new Qt installer 4.0 CLI interface
  #
  cd /usr/src && \
  INSTALLER=qt-online-installer-linux-x64-online.run && \
  curl -LO https://download.qt.io/official_releases/online_installers/${INSTALLER} && \
  chmod u+x ${INSTALLER} && \
  # See CLI parameters here: https://wiki.qt.io/Online_Installer_4.x
  ./${INSTALLER} \
    install \
      qt.qt6.680.linux_gcc_64 \
      qt.qt6.680.addons.qt5compat.linux_gcc_64 \
      extensions.qtwebengine.680.linux_gcc_64 \
    --root /opt/qt \
    --email ${QT_ACCOUNT_LOGIN} \
    --pw ${QT_ACCOUNT_PASSWORD} \
    --verbose \
    --platform minimal \
    --accept-licenses \
    --accept-obligations \
    --confirm-command \
    --auto-answer telemetry-question=No,AssociateCommonFiletypes=No,installationErrorWithCancel=Ignore,OverwriteTargetDirectory=No &&\
  rm -f qt-unified-linux-x64-online.run && \
  # Cleanup
  #
  find /opt/qt -maxdepth 1 -type f -exec rm -rf "{}" \; && \
  find /opt/qt -type f -name "*.debug" -delete && \
  find /opt/qt/6.8.0/gcc_64/bin -type f -executable -exec strip {} \; && \
  rm -rf \
    /opt/qt/dist \
    /opt/qt/Docs \
    /opt/qt/Examples \
    /opt/qt/Tools \
  && \
  #
  # Cleanup
  #
  dnf clean all && \
  rm -rf /var/cache/dnf

#
# (1) Add Qt root directory to the PATH. This allows CMake command
#     'find_package(Qt5 REQUIRED)` to succeed.
#
# (2) Set env. variable Qt5_DIR to support configuring project
#     by explicitly passing -DQt5_DIR:PATH=${Qt5_DIR}
#
ENV PATH=/opt/qt/6.8.0/gcc_64/:${PATH} \
    Qt6_DIR=/opt/qt/6.8.0/gcc_64/lib/cmake/Qt6

#include "common.label-and-env"
